# Generated by Django 3.1.3 on 2020-11-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeediem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedIem',
            new_name='ProfileFeedItem',
        ),
    ]
